# Generated by Django 4.2.16 on 2024-10-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('product_code', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(default=0)),
                ('get', models.IntegerField(default=0)),
            ],
        ),
    ]
