# Generated by Django 4.2.16 on 2024-10-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_customer_customer_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_since',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
